version: '3.8'

services:
  front:
    container_name: front
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        - PORT=3000
    restart: on-failure
    ports:
      - '3000:3000'